---
- name: Required packages are installed
  become: true
  package: name=epel-release

- name: Install openvpn
  become: true
  yum:
    name:
      - openvpn
      - openssl
      - python-pip
    state: latest
    update_cache: true

- name: Certificate Authority is generated
  import_tasks: ca.yml

- name: Server is configured
  import_tasks: server.yml

- name: Client is configured
  import_tasks: client.yml

- name: Iptables rules are configured
  import_tasks: iptables.yml
  tags: iptables
...
