---
- name: Required packages are installed
  become: true
  package:
    name: epel-release

- name: Install openvpn
  become: true
  yum:
    name:
      - openvpn
      - openssl
      - python-pip
    state: latest
    update_cache: true

- name: Certificate Authority is generated
  include_tasks: ca.yml

- name: Server is configured
  include_tasks: server.yml

- name: Client is configured
  include_tasks: client.yml
...
