---
- name: Required packages are installed
  become: true
  package:
    name:
      - epel-release
      - openvpn
      - python-pip

- name: Certificate Authority is generated
  include_tasks: ca.yml

- name: Server is configured
  include_tasks: server.yml

- name: Client is configured
  include_tasks: client.yml
...
