---
- name: Server private key is generated
  become: true
  openssl_privatekey:
    path: /etc/openvpn/server.key

- name: Server certificate request is generated
  become: true
  openssl_csr:
    path: /etc/openvpn/server.csr
    privatekey_path: /etc/openvpn/server.key
    common_name: epsivpn

- name: Server ceritificate is generated
  become: true
  openssl_certificate:
    path: /etc/openvpn/server.crt
    csr_path: /etc/openvpn/server.csr
    ownca_path: /root/ca/ca.crt
    ownca_privatekey_path: /root/ca/ca.key
    provider: ownca

- name: Generate DH Parameters with a different size (2048 bits)
  become: true
  openssl_dhparam:
    path: /etc/openvpn/dh.pem
    size: 2048

- name: Configure openvpn
  become: true
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644

- name: Enable ip forward
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
  notify: restart network

- name: TLS encryption keys are generated
  become: true
  command:
    cmd: "openvpn --genkey --secret /etc/openvpn/{{ server_name }}.tlsauth"
    creates: "/etc/openvpn/{{ server_name }}.tlsauth"
...
